version: '3.8'
services:
  app:
    image: node:22-alpine
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules  # Protege node_modules do container
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    stdin_open: true
    tty: true
    environment:
      - NODE_ENV=development  # Define modo de desenvolvimento
